### ISSUE TITLE
Moped ignores Mopidy album images

### ISSUE THREAD

**Issue by tkem** [martijnboland/moped#17]
AFAICS, Moped ignores image URIs provided by `mopidy.models.Album.images`, and always tries to fetch images from last.fm.

Extensions like Mopidy-InternetArchive or Mopidy-Podcast provide their own images (if available), which you will not necessarily find on last.fm. Mopidy v0.20 will provide links to coverartarchive.org images if the album has a proper `musicbrainz_id`. Local library extension like Mopidy-Local-SQLite can extract images from local media files and provide them via Mopidy's integrated Web server, reducing bandwidth *and* providing larger/better reolution images. Etc., etc. I guess, you get the idea ;-)

**Comment by martijnboland** [comment]
Fixed, see issue #34.
