### ISSUE TITLE
Use album artwork returned from Mopidy

### ISSUE THREAD

**Issue by kingosticks** [martijnboland/moped#34]
I've recently updated the Mopidy-Tunein extension to return radio station logo images in the response as a Track's Album image. This works nicely in musicbox-webclient but not in Moped. I've noticed that Moped tries to get the album artwork from last.fm and completely ignores the `Album`'s `images` field. It would be nice if it use the Album image in the returned Track if it's set.

Example TuneIn tl_track: 
```
tl_track":{"track":{"album":{"images":["http://d1i6vahw24eb07.cloudfront.net/s25419q.png"],"__model__":"Album","uri":"tunein:station:s25419","name":"BBC Radio 4"},"__model__":"Track","artists":[{"__model__":"Artist","name":"GF Newman\'s The Corrupted"}],"name":"BBC Radio 4","uri":"tunein:station:s25419"},"__model__":"TlTrack","tlid":49}},"jsonrpc":"2.0","id":2231}
```

**Comment by martijnboland** [comment]
Btw, do you know any other backend that leverages the album's images besides TuneIn? TuneIn artwork works fine now, but I'm just curious if there are others.

**Comment by kingosticks** [comment]
Thanks! I don't know of any others but I only personally use Spotify and TuneIn. However, It looks like things may soon change in the artwork department anyway: https://github.com/mopidy/mopidy-spotify/issues/23

**Comment by kingosticks** [comment]
it seems the main issue at https://github.com/mopidy/mopidy/issues/263 is more useful. Apparently Soundcloud sets the album's images field.

**Comment by tkem** [comment]
FYI: Mopidy-Local-Images, Mopidy-Podcast and Mopidy-InternetArchive all provide `album.images`.

**Comment by kingosticks** [comment]
It's also worth noting that the v0.20 release of Mopidy will include a [get_images](https://docs.mopidy.com/en/develop/api/core/#mopidy.core.LibraryController.get_images) API call.
