### ISSUE TITLE
clear_current_track argument to mopidy.playback.stop() is deprecated

### ISSUE THREAD

**Issue by jodal** [martijnboland/moped#38]
The `clear_current_track` argument to `mopidy.playback.stop()` is deprecated. As it was a internal detail that leaked out through the API, it is currently removed in Mopidy's develop branch. Now, we've discovered that removing this breaks Moped. The release of Mopidy 0.20 is imminent, and I think the options are:

- Readd `clear_current_track` as an argument to `stop()`, but without any effect, before Mopidy 0.20 is released, or
- Change Moped to not use `clear_current_track`.

Is this a quick fix for you?

**Comment by martijnboland** [comment]
That'd be a quick fix. Hang on...

**Comment by martijnboland** [comment]
clear_current_track param is removed and version #0.4.4 is released.

**Comment by jodal** [comment]
Thanks :-)
