### ISSUE TITLE
add album to playlist

### ISSUE THREAD

**Issue by simsasaile** [martijnboland/moped#43]
Hi, moped looks really neat, I just can't find out how to add an album to the playlist or to create a new playlist. At the moment I can only add single tracks from `browse -> local media` but that's not very comfortable.

Is that not possible?

CU, Simsi

**Comment by martijnboland** [comment]
This is not possible right now. By design we do not support adding or removing tracks to the current playlist. However, when browsing an selecting a track for playing, all adjacent files (the album) should be added to the playlist too. If not, then this is a bug.

**Comment by simsasaile** [comment]
Ah ok, now I understand the concept! It's a design with simplicity in mind, that's cool.
But what tool do you use to create playlist, an external MPD-Client?

**Comment by martijnboland** [comment]
No, the playTrack() function accepts a second parameter with all tracks that should be added to the playlist. So when playing a single track from an album, a playlist with all album tracks is created.

**Comment by simsasaile** [comment]
Ok, thanks for clarification! As it reacts as it is designed to do, I will close this issue.
