### ISSUE TITLE
Volume Slider Not Working With Mouse On Chrome (Windows)

### ISSUE THREAD

**Issue by sdelgran** [martijnboland/moped#44]
First of all, thank you for a great piece of software!

Issue with Chrome Version 42.0.2311.135 m on Windows 8.1 64 bit and moped 0.5.0.

I cannot control the volume slider with the mouse. Tapping the touchscreen works fine.

The volume slider works just fine with IE11 on the same machine or Chrome 42.0.2311.111 on Android.

**Comment by martijnboland** [comment]
Unfortunately, I cannot reproduce this. Tested with the same Chrome version on both Windows 8.1 64 and Windows 7 64.

**Comment by d00d13** [comment]
Works for me.

**Comment by martijnboland** [comment]
I'm sorry, but this issue is a little bit too vague and doesn't seem to happen consistently.

**Comment by sdelgran** [comment]
No problem martijn. I still happens on my machine but I can't see why it should...

**Comment by ElessarWebb** [comment]
Same here using latest version from pip

**Comment by mattaereal** [comment]
Same here. Latest version from pip on Linux with Chromium,

~ $ chromium --version                                                                            
Chromium 57.0.2987.133
