### ISSUE TITLE
No possibility to stop playback

### ISSUE THREAD

**Issue by martinschilliger** [martijnboland/moped#45]
Maybe I missed it somewhere - but in Moped there is no possibility to stop playback vom Mopidy. One can only pause playback.

**Comment by martijnboland** [comment]
I'm finding it hard to justify the addition of a stop button. Is there a problem with only having a pause button?

**Comment by martinschilliger** [comment]
I stream the output via a node.js hub over my network to the Airport Express. So while staying in pause the Airport is still occupied by mopidy and therefore not ready to receive music from other sources. When stoping the output the Airport gets released.
Maybe I'm the only one affected - so don't change it only for me. I like your concept of keeping it simple. ;-)

**Comment by kingosticks** [comment]
While paused, Mopidy (gstreamer) will hog the alsasink on some systems and block other applications from using it. This came up again recently here https://github.com/mopidy/mopidy/issues/1384. IMO it's worth including it (musicbox-webclient will be).

**Comment by martijnboland** [comment]
Alright, that's a good reason to add a stop button

**Comment by martinschilliger** [comment]
Cool. :-)

**Comment by dony71** [comment]
I'm using latest released Mopidy-Moped (0.6.4)  but still couldn't find any stop button
Is this implemented in unreleased version? Where I can get this ?

**Comment by martijnboland** [comment]
Still unreleased, I'll create a release soon. In  the meantime you can get the current version from https://github.com/martijnboland/moped/tree/master/dist
