### ISSUE TITLE
Switch Song - missing updates in GUI

### ISSUE THREAD

**Issue by Elompenta** [martijnboland/moped#48]
If I Switch the song via Browser the following Things are not updated on your current trunk Version
- Picture
- Artist
- Song title

Also the blue Background of the active song is not set

Testen on:
- Windows IE
- Windows Chrome
- Windowsphoen IE

I I relaod the page all song ans Artist informations are correct, but no active title is markes with blue background

**Comment by martijnboland** [comment]
Unable to reproduce this and the issue is > 2 years old -> closing
