### ISSUE TITLE
Moped is slow to give access to the player on startup

### ISSUE THREAD

**Issue by Richard-Walker** [martijnboland/moped#49]
When I open the app, it takes maybe 20 seconds to load.
Only after that I can access the player.

This is very inconvenient because sometimes you just want to pause music to answer a phone call. Other web clients are much faster to give access to the player.

I am using Spotify with a lot of playlists (126). Some of them containing hundreds of songs (starred songs for instance). Also I am using a folder structure to keep things organised.

Moped, at the difference of other web clients, features a folder structure for playlists. I wonder if this is the reason it is slower? Because it would need to parse and create the structure on every start-up?

**Comment by Richard-Walker** [comment]
Looking at the code, I have the feeling that the processPlaylists() & ensureFolderExists() could be optimised.

**Comment by Richard-Walker** [comment]
Forgot to mention that I am running mopidy on Raspberry Pi B+ which is not the fastest machine ;)

**Comment by martijnboland** [comment]
I'll have a look at it. The playlists should be loaded asynchronously.

**Comment by martijnboland** [comment]
It seems that the order in which commands are sent to Mopidy matter. When Moped receives the 'state:online' event, a whole lot of commands are sent, including 'load playlists'. This command is usually one of the first being sent and I get the impression that loading a huge amount of playlists blocks all other commands.

**Comment by martijnboland** [comment]
Loading of playlists is delayed with 200-300 ms, so other commands are sent before playlist loading command. See commit 4aca6c152cfc94a9c8128e51841748fdfa1d1346

**Comment by Richard-Walker** [comment]
Thanks Martijn,

I want to try it :)

How should I do?
Shall I set-up a development environment?
Is it possible to do it on my mac without installing Mopidy (I would connect to the instance on my raspberry pi)?

**Comment by Richard-Walker** [comment]
Hi Martijn,

I got it!

I compared the request sent by another client with moped.

Other client:
`{"method":"core.playlists.get_playlists","params":[false],"jsonrpc":"2.0","id":10}`
Moped:
`{"method":"core.playlists.get_playlists","jsonrpc":"2.0","id":3}`

In the end moped got all the track lists of all playlists in the response. Which is huge in my case.
It is 2MB against 20KB.

Also, I observed that requests seem to be served on a FIFO manner by the server.
Hence, if you request something greedy, it will queue the next requests.

Hope that helps.

Richard

**Comment by martijnboland** [comment]
Alright, good find! I'll change it so that not all tracks are loaded up
front

**Comment by adamcik** [comment]
The server is built using an actor model, so each request gets added to the core "inbox" which will be processed in a FIFO manner, so clients asking for something expensive will block other commands.

The default client in pimusicbox also had this issue, which is why we ended up adding the `include_tracks=False` option to give a backwards compatible way of slimming the request down a lot.

Otherwise I would recommend looking at https://docs.mopidy.com/en/latest/api/core/#mopidy.core.PlaylistsController.as_list which gives just the name of the playlist as the get_playlists is probably going away (and is currently implemented as a shim around `as_list` anyway).

**Comment by martijnboland** [comment]
Thanks for the suggestion. I'll use as_list then.

**Comment by martijnboland** [comment]
Version 0.6.1 is released that uses as_list instead of get_playlists.

**Comment by martijnboland** [comment]
@Richard-Walker has the issue been fixed with 0.6.1?

**Comment by martijnboland** [comment]
No news is good news, closing the issue.

**Comment by Richard-Walker** [comment]
Hi Martijn,

Sorry for the lack of reactivity.
But yes it works!

I haven’t used Moped in a while but I am planning to use it intensively in the future when I restart my home server project.
From my experience with Moped (months ago), I have noticed some glitches when using it as a home screen app on the iphone.
The playback buttons sometimes do not respond. The experience was not as good as when using it on the desktop.

Don’t know if it has been fixed...
Anyways, I will give more details when I reopen my project.

KR,

Richard

**Comment by martijnboland** [comment]
Hi Richard

I'm using it also as a homescreen app on iPhone. It kind of feels that the first click on the the playback buttons initiate the hover effect and a second click is required to actually perform the action. 
What has been fixed however is the back button.

**Comment by Richard-Walker** [comment]
Yes, that makes sense. Would be nice to disable the hover on mobile then.

Also, if I remember well, some troubles could occur when waking-up app from background...
