### ISSUE TITLE
Cannot remove radio

### ISSUE THREAD

**Issue by Chateaudur** [martijnboland/moped#50]
Hello,

Thanks a lot for the interface, it's great and very clear :) 
A little issue though is that I cannot find how to remove a radio from the starred radio list. Could you tell me how to do it, which file to edit or something, or maybe provide a delete icon a starred radio?

Thank you :)

**Comment by martijnboland** [comment]
Select the radio station and hit the "Unstar" button that is located next to the "Play" button
