### ISSUE TITLE
Display filenames when metadata is not present

### ISSUE THREAD

**Issue by kgudka** [martijnboland/moped#51]
Thanks for this great Mopidy web client!

I'm using Mopidy to play wav files which (obviously) don't have metadata in them. Would it be possible to display filenames when no metadata is present?

**Comment by martijnboland** [comment]
That would probably be something for the Mopidy guys. Moped just consumes the data generated by Mopidy and displays the name of an item. We can't influence whether that's from meta-data or a file name. https://github.com/mopidy/mopidy/issues
