### ISSUE TITLE
firefox stuck at "Status: {{connectionState}}"

### ISSUE THREAD

**Issue by haselwarter** [martijnboland/moped#53]
Hi, when I bring up http://localhost:6680/moped/#/ only the frame of the interface is displayed and "Status: {{connectionState}}" shows up in the top right corner. I'm on arch linux with mopidy 1.1.0 and moped 0.6.1, firefox 40.0. I tried to run firefox in safe-mode, doesn't help.
With chrome everything works fine.

here's the trace from the ff console

11:49:26.310 Error: An invalid or illegal string was specified
[22]</c.prototype.connect@http://localhost:6680/moped/assets/moped-0.6.1.js:9:21540
c@http://localhost:6680/moped/assets/moped-0.6.1.js:9:19545
.start@http://localhost:6680/moped/assets/moped-0.6.1.js:19:13610
@http://localhost:6680/moped/assets/moped-0.6.1.js:18:30492
e@http://localhost:6680/moped/assets/moped-0.6.1.js:13:6684
bc/this.$get</</<@http://localhost:6680/moped/assets/moped-0.6.1.js:13:27529
v/<@http://localhost:6680/moped/assets/moped-0.6.1.js:13:18291
f@http://localhost:6680/moped/assets/moped-0.6.1.js:12:22084
v@http://localhost:6680/moped/assets/moped-0.6.1.js:13:18275
h@http://localhost:6680/moped/assets/moped-0.6.1.js:13:14344
F/<@http://localhost:6680/moped/assets/moped-0.6.1.js:13:13840
_/h/</<@http://localhost:6680/moped/assets/moped-0.6.1.js:12:27771
Vc/this.$get</n.prototype.$eval@http://localhost:6680/moped/assets/moped-0.6.1.js:14:22156
Vc/this.$get</n.prototype.$apply@http://localhost:6680/moped/assets/moped-0.6.1.js:14:22381
_/h/<@http://localhost:6680/moped/assets/moped-0.6.1.js:12:27729
e@http://localhost:6680/moped/assets/moped-0.6.1.js:13:6684
_/h@http://localhost:6680/moped/assets/moped-0.6.1.js:12:27650
_@http://localhost:6680/moped/assets/moped-0.6.1.js:12:27936
$@http://localhost:6680/moped/assets/moped-0.6.1.js:12:27185
@http://localhost:6680/moped/assets/moped-0.6.1.js:16:24973
_.Callbacks/k@http://localhost:6680/moped/assets/moped-0.6.1.js:11:4633
_.Callbacks/l.fireWith@http://localhost:6680/moped/assets/moped-0.6.1.js:11:5450
.ready@http://localhost:6680/moped/assets/moped-0.6.1.js:11:7243
g@http://localhost:6680/moped/assets/moped-0.6.1.js:10:2190
1 moped-0.6.1.js:14:9432
e/<() moped-0.6.1.js:14
dc/this.$get</<() moped-0.6.1.js:13
Vc/this.$get</n.prototype.$apply() moped-0.6.1.js:14
_/h/<() moped-0.6.1.js:12
e() moped-0.6.1.js:13
_/h() moped-0.6.1.js:12
_() moped-0.6.1.js:12
$() moped-0.6.1.js:12
<anonymous> moped-0.6.1.js:16
_.Callbacks/k() moped-0.6.1.js:11
_.Callbacks/l.fireWith() moped-0.6.1.js:11
.ready() moped-0.6.1.js:11
g() moped-0.6.1.js:10

**Comment by martijnboland** [comment]
Very hard to reproduce this issue. On Firefox 40, Mac everything works fine. Could you probably create a non-release build try that one out on Arch Linux? Just follow the steps under 'Development' in the Readme.rst.

**Comment by mattjbourque** [comment]
I have experienced a similar issue. I have used various browsers on various computers & mobile devices, and found the following pattern: the first time I use Moped, everything works fine, and appears to continue to work unless I click "Settings" then "Verify connection" then "Save settings." After this, I get only the frame of the interface with "Status: {{connectionState}}" displayed as described in the original post.

The first time I did this I was just poking around, but I've been able to reproduce it using Firefox on and Chrome on Ubuntu, and also Android Firefox.

Clearing the browsers' application cache and cookies doesn't fix the problem.

**Comment by martijnboland** [comment]
I've tried everything I could, but I cannot reproduce this issue. It has probably something to do with the Mopidy configuration. Could you give some details? Mopidy version, OS, plugins used etc.

**Comment by BoudewijnGlas** [comment]
I was able to reproduce this in firefox 45.02. In my case it was related to the Noscript (v 2.9.011) plugin I use in combination with mDNS i believe.

It works in firefox when I access the moped server on the IP. When I try to connect it with the .local address that mDNS gives via the Ubuntu machine it is installed on it fails with the above error in Firefox with Noscript even with the .local address white listed.

**Comment by jobvanes** [comment]
I have this issue using Safari Browser on my mac.

**Comment by martijnboland** [comment]
I have been able to reproduce it by saving settings without entering a mopidy url. This will set the value of 'moped.mopidyUrl' in LocalStorage to undefined. Clearly a bug. Could you check in your LocalStorage if this is also the case?
