### ISSUE TITLE
"karma.configure is not a function"

### ISSUE THREAD

**Issue by getignited** [martijnboland/moped#57]
Hi there,

Just been following the steps to setup a development environment for the app - cloned, npm + bower installled, and then ran grunt watch. Was presented with the following:

Error in config file!
[TypeError: karma.configure is not a function]
TypeError: karma.configure is not a function

Any idea how to get around this? I haven't modified any files, other than installing. Karma had to be installed separately using npm install karma, despite having run the install globally previously.

Any help would be much appreciated! Cheers.

**Comment by martijnboland** [comment]
Can you give it another try? It should be fixed now. The karma template used the .configure() function that has been deprecated long ago and is probably removed in a recent karma version.
