### ISSUE TITLE
Add a "Home" link in the sidebar

### ISSUE THREAD

**Issue by allo-** [martijnboland/moped#58]
I am always confused for a moment where the "home" link is, because its small at top while the rest of navigation is in the Sidebar. I think it should be added to the top of the sidebar, so you're seeing it directly and its a bigger link.

**Comment by martijnboland** [comment]
The main reason it's there is for phone use when the sidebar isn't visible. I'm not sure about moving the home link. Are more people having issues with this?

**Comment by allo-** [comment]
Add it and keep the other one. Both places have enough space for it, don't they?

**Comment by martijnboland** [comment]
I'm sorry, I've given it a bit more thought, but this isn't going to change.
