### ISSUE TITLE
Status : Offline

### ISSUE THREAD

**Issue by FromBabylon** [martijnboland/moped#60]
Hi,

I installed moped so as to use the mopidy-youtube extension. However the page stated "Status Offline" in the upper right corner. 

What did I do wrong ? 

Thanks

**Comment by martijnboland** [comment]
Status Offline usually indicates that a JavaScript error occurred. Could you open the console in your browser and check for errors?

**Comment by FromBabylon** [comment]
I misconfigured the settings, everything works now 

You can close
