### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by busbauen** [martijnboland/moped#61]
Hey
I get an error during the install of moped. I removed lines 23-28 in README.rst but I still get the error. I have no clue what to change or test. I'm using Arch Linux.

[root@arch-himbeere moped]# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    long_description=open('README.rst').read(),
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3682: ordinal not in range(128)

Thank You!

**Comment by martijnboland** [comment]
To be honest, I don't know much about the Python setup scripts. @jodal, have you seen this before?

**Comment by jodal** [comment]
@busbauen From your hostname `arch-himberee` I'm guessing that you're running Arch, thus `python` means Python 3. Mopidy and Mopidy extensions still only supports Python 2.7, so you should run `python2.7 setup.py install`.

**Comment by busbauen** [comment]
solved! thx
