### ISSUE TITLE
Can't modify playlist (change order, delete items)

### ISSUE THREAD

**Issue by axelsimon** [martijnboland/moped#64]
Hi!
Unless I'm missing something, I can't change the playlist once it's been populated.

Especially, if you start playing a song from search results, songs might be added to the playlist that you don't actually want to listen ton but there is no way to delete them.

Thanks!

**Comment by martijnboland** [comment]
This is by design. I found the playlist/queue concept of the other players very confusing, so I tried to automatically manage the queue behind the scenes. 
In case of search results, this doesn't work very nice. Room for improvement indeed.

**Comment by axelsimon** [comment]
Hi again, I was giving moped another spin today and came back to this issue. I'm trying to understand how you envision moped being used.

Here's my use case: I start playing an album and decide that I'd like to hear another one after this one, so I want to enqueue it. However, if I click on the first song of album \#2, it just plays that instead, and I can't chose to add the album as a whole.

So, this might be by design, but in my case it means I can only listen to one album at a time using moped, and then I have to go play album 2 once I've finished listening to album 1. Essentially, that sort of brings us back to having to get up to go put CD \#2 in the CD player once CD \#1 has reached its end 😉 

Am I missing something?

**Comment by martijnboland** [comment]
No, you're not missing something. This is by design.

**Comment by axelsimon** [comment]
One album at a time? Ok then, moped is not for me.

We can close this issue I think, thanks for answering.

**Comment by martijnboland** [comment]
Yes, one album at a time unfortunately.
