### ISSUE TITLE
How to run locally?

### ISSUE THREAD

**Issue by thegreatmichael** [martijnboland/moped#66]
So i see https://github.com/martijnboland/moped#development but how do i get my local mopidy to know about this thing? i tried to do `sudo pip install -e <moped_dir>/mopidy_moped`, but `<moped_dir>/mopidy_moped is not installable. File 'setup.py' not found.`

**Comment by thegreatmichael** [comment]
wait a minute, i was in the wrong dir, i did it from `<moped_dir>` and the install worked, but I still don't see it listed as a frontend when i start mopidy...

**Comment by thegreatmichael** [comment]
ok team, i think my problem is this python2/3 cluster. I did it once more with `pip2.7 install -e <moped_dir>` and at least mopidy seems to know about moped now. (though it isn't grabbing any spotify info yet (with account details in `~/.config/mopidy/mopidy.conf`)

**Comment by martijnboland** [comment]
Can you see that it is using Spotify when starting Mopidy in a console? Or perhaps the people at https://discuss.mopidy.com/ can help you forward.

**Comment by thegreatmichael** [comment]
looks like i had failed to `brew install mopidy-spotify` d-oh! i need the spotify backend to listen to spotify!
