### ISSUE TITLE
Install without sudo?

### ISSUE THREAD

**Issue by rnkn** [martijnboland/moped#67]
Could you please provide some guidance for how to install without `sudo` for users without administrator access or those who want to keep their system consistent?

I'm on a Mac, so for me, adding to https://github.com/mopidy/homebrew-mopidy would be quite very helpful.

**Comment by MarcinWieczorek** [comment]
You should try to install it locally with pip.

**Comment by rnkn** [comment]
For some reason my system doesn't have pip ☹️

I found a way to install it here https://github.com/dirkgroenen/mopidy-mopify/issues/211
