### ISSUE TITLE
Search field and quotation marks

### ISSUE THREAD

**Issue by RensBloom** [martijnboland/moped#69]
Currently the search field doesn't work the way I would expect, at least together with the common-used spotify plugin for mopidy. Without quotation marks the behaviour is as I would expect with quotation marks, and vice versa.
An example:
If I enter _Beethoven penny_ I can't find anything. If I add quotation marks, e.g. _"Beethoven penny"_, a lot of results are found although now result has the word _Beethoven_ directly followed by _penny_.

**Comment by martijnboland** [comment]
Well spotted! I always thought the search function of Mopidy just wasn't that good *ducks*. Going to fix that asap.
