### ISSUE TITLE
Can't find "Your Music" menu for Spotify

### ISSUE THREAD

**Issue by mikegilchrist** [martijnboland/moped#73]
I apologize if I'm missing something simple, but I am running moped on a RPi and appear to have [spotify] and  [spotify_tunigo] configured correctly since I can access some spotify resources.

The one thing I can't find are the "My Music" category and subcategory that I have on my spotify client.

Is there a way to configure this as a user?

**Comment by kingosticks** [comment]
It's not available as the library mopidy-spotify uses to talk to Spotify does not support this feature.
