### ISSUE TITLE
404 Error page

### ISSUE THREAD

**Issue by amiut** [martijnboland/moped#75]
It gives me a 404 error when i navigate to `http://localhost:6680/moped`

```
Arch linux
mopidy-git
```

**Comment by wt9bind** [comment]
Me too. I can't seem to work out why, everything appears to be installed correctly

**Comment by martijnboland** [comment]
I'm sorry to hear that. What environment are you using (OS, Python version, Mopidy from apt-get or pip)?

**Comment by wt9bind** [comment]
Hi Martin,

I am running Raspbian Stretch
Python: 2.7.13
I installed mopidy via apt.

I should also mention, that I am running Iris on localhost:6680/iris with no problem.

Thank you

**Comment by martijnboland** [comment]
And is moped listed when you navigate to http://localhost:6680?

**Comment by wt9bind** [comment]
No, actually it isn't. 
`
Web clients
images
iris
Web clients which are installed as Mopidy extensions will automatically appear here.
`
But when I run:
`
pi@SpotiPi:~ $ sudo pip install Mopidy-Moped
`
It returns:
`
Requirement already satisfied: Mopidy-Moped in /usr/local/lib/python3.4/dist-packages
Requirement already satisfied: Mopidy>=1.0.0 in /usr/local/lib/python3.4/dist-packages (from Mopidy-Moped)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from Mopidy-Moped)
Requirement already satisfied: requests>=2.0 in /usr/lib/python3/dist-packages (from Mopidy>=1.0.0->Mopidy-Moped)
Requirement already satisfied: tornado>=3.2 in /usr/local/lib/python3.4/dist-packages (from Mopidy>=1.0.0->Mopidy-Moped)
Requirement already satisfied: Pykka>=1.1 in /usr/local/lib/python3.4/dist-packages (from Mopidy>=1.0.0->Mopidy-Moped)
Requirement already satisfied: backports-abc>=0.4 in /usr/local/lib/python3.4/dist-packages (from tornado>=3.2->Mopidy>=1.0.0->Mopidy-Moped)
pi@SpotiPi:~ $ 
`

**Comment by kingosticks** [comment]
Mopidy is python, not python 3. For arch that means `sudo pip2 install mopidy-moped`, I think.

**Comment by wt9bind** [comment]
I tried running the command and got:
`
pi@SpotiPi:~ $ sudo pip2 install mopidy-moped
Traceback (most recent call last):
  File "/usr/bin/pip2", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip2')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
pi@SpotiPi:~ $ 
`

**Comment by kingosticks** [comment]
You need to update pip2

**Comment by wt9bind** [comment]
Still no good, unfortunately:

pi@SpotiPi:~ $ sudo apt-get install python-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 173 not upgraded.
pi@SpotiPi:~ $ sudo apt-get install --reinstall python-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 173 not upgraded.
Need to get 114 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://mirrordirector.raspbian.org/raspbian/ jessie/main python-pip all 1.5.6-5 [114 kB]
Fetched 114 kB in 2s (52.8 kB/s)     
(Reading database ... 114244 files and directories currently installed.)
Preparing to unpack .../python-pip_1.5.6-5_all.deb ...
Unpacking python-pip (1.5.6-5) over (1.5.6-5) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up python-pip (1.5.6-5) ...
pi@SpotiPi:~ $ sudo pip2 install mopidy-moped
Traceback (most recent call last):
  File "/usr/bin/pip2", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip2')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
pi@SpotiPi:~ $

**Comment by wt9bind** [comment]
I uninstalled pip2, reinstalled and then ran the following:
pi@SpotiPi:~ $ sudo pip2 install Mopidy-Moped
Downloading/unpacking Mopidy-Moped
  Downloading Mopidy-Moped-0.7.1.tar.gz (395kB): 395kB downloaded
  Running setup.py (path:/tmp/pip-build-OGdeFC/Mopidy-Moped/setup.py) egg_info for package Mopidy-Moped
    warning: no previously-included files found matching '.bowerrc'
    warning: no previously-included files found matching '*.tpl'
    warning: no previously-included files found matching '*.json'
    warning: no previously-included files found matching 'build.config.js'
    warning: no previously-included files found matching 'Gruntfile.js'
    warning: no previously-included files found matching 'ext.conf'
    warning: no previously-included files matching '*' found under directory 'build'
    warning: no previously-included files matching '*' found under directory 'dist'
    warning: no previously-included files matching '*' found under directory 'karma'
    warning: no previously-included files matching '*' found under directory 'node_modules'
    warning: no previously-included files matching '*' found under directory 'screenshots'
    warning: no previously-included files matching '*' found under directory 'src'
    warning: no previously-included files matching '*' found under directory 'vendor'
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/dist-packages (from Mopidy-Moped)
Requirement already satisfied (use --upgrade to upgrade): Mopidy>=1.0.0 in /usr/lib/python2.7/dist-packages (from Mopidy-Moped)
Requirement already satisfied (use --upgrade to upgrade): Pykka>=1.1 in /usr/lib/python2.7/dist-packages (from Mopidy>=1.0.0->Mopidy-Moped)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.0 in /usr/local/lib/python2.7/dist-packages (from Mopidy>=1.0.0->Mopidy-Moped)
Requirement already satisfied (use --upgrade to upgrade): tornado>=3.2 in /usr/local/lib/python2.7/dist-packages (from Mopidy>=1.0.0->Mopidy-Moped)
Requirement already satisfied (use --upgrade to upgrade): singledispatch in /usr/local/lib/python2.7/dist-packages (from tornado>=3.2->Mopidy>=1.0.0->Mopidy-Moped)
Requirement already satisfied (use --upgrade to upgrade): certifi in /usr/local/lib/python2.7/dist-packages (from tornado>=3.2->Mopidy>=1.0.0->Mopidy-Moped)
Requirement already satisfied (use --upgrade to upgrade): backports_abc>=0.4 in /usr/local/lib/python2.7/dist-packages (from tornado>=3.2->Mopidy>=1.0.0->Mopidy-Moped)
Installing collected packages: Mopidy-Moped
  Running setup.py install for Mopidy-Moped
    warning: no previously-included files found matching '.bowerrc'
    warning: no previously-included files found matching '*.tpl'
    warning: no previously-included files found matching '*.json'
    warning: no previously-included files found matching 'build.config.js'
    warning: no previously-included files found matching 'Gruntfile.js'
    warning: no previously-included files found matching 'ext.conf'
    warning: no previously-included files matching '*' found under directory 'build'
    warning: no previously-included files matching '*' found under directory 'dist'
    warning: no previously-included files matching '*' found under directory 'karma'
    warning: no previously-included files matching '*' found under directory 'node_modules'
    warning: no previously-included files matching '*' found under directory 'screenshots'
    warning: no previously-included files matching '*' found under directory 'src'
    warning: no previously-included files matching '*' found under directory 'vendor'
  Could not find .egg-info directory in install record for Mopidy-Moped
Successfully installed Mopidy-Moped
Cleaning up...
pi@SpotiPi:~ $ 

Still no good unfortunately.

**Comment by kingosticks** [comment]
The pip in APT is very old. The best way to update is usually through pip itself. I don't understand what got python3 involved under a Raspbian system, that should not happen.

Does it not appear in the output of `sudo mopidyctl deps`?

**Comment by wt9bind** [comment]
pi@SpotiPi:~ $ sudo mopidyctl deps
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf deps" as user mopidy
Executable: /usr/bin/mopidy
Platform: Linux-4.4.50-v7+-armv7l-with-debian-8.0
Python: CPython 2.7.9 from /usr/lib/python2.7
Mopidy: 2.1.0 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  requests>=2.0: 2.18.4 from /usr/local/lib/python2.7/dist-packages
    certifi>=2017.4.17: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
    chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/lib/python2.7/dist-packages
    idna<2.7,>=2.5: 2.6 from /usr/local/lib/python2.7/dist-packages
    urllib3<1.23,>=1.21.1: 1.22 from /usr/local/lib/python2.7/dist-packages
  tornado>=3.2: 4.5.3 from /usr/local/lib/python2.7/dist-packages
    singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
      six: 1.11.0 from /usr/local/lib/python2.7/dist-packages
    certifi: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
    backports_abc>=0.4: 0.5 from /usr/local/lib/python2.7/dist-packages
Mopidy-ALSAMixer: 1.0.3 from /usr/lib/python2.7/dist-packages
  Mopidy>=0.19: 2.1.0 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests>=2.0: 2.18.4 from /usr/local/lib/python2.7/dist-packages
      certifi>=2017.4.17: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
      chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/lib/python2.7/dist-packages
      idna<2.7,>=2.5: 2.6 from /usr/local/lib/python2.7/dist-packages
      urllib3<1.23,>=1.21.1: 1.22 from /usr/local/lib/python2.7/dist-packages
    tornado>=3.2: 4.5.3 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.11.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
      backports_abc>=0.4: 0.5 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  pyalsaaudio: 0.7 from /usr/lib/python2.7/dist-packages
Mopidy-Iris: 3.11.0 from /usr/local/lib/python2.7/dist-packages
  setuptools>=3.3: 38.4.0 from /usr/local/lib/python2.7/dist-packages
  pylast>=1.6.0: 2.0.0 from /usr/local/lib/python2.7/dist-packages
    six: 1.11.0 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=2.0: 2.1.0 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests>=2.0: 2.18.4 from /usr/local/lib/python2.7/dist-packages
      certifi>=2017.4.17: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
      chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/lib/python2.7/dist-packages
      idna<2.7,>=2.5: 2.6 from /usr/local/lib/python2.7/dist-packages
      urllib3<1.23,>=1.21.1: 1.22 from /usr/local/lib/python2.7/dist-packages
    tornado>=3.2: 4.5.3 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.11.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
      backports_abc>=0.4: 0.5 from /usr/local/lib/python2.7/dist-packages
  Mopidy-Local-Images>=1.0: 1.0.0 from /usr/local/lib/python2.7/dist-packages
    uritools>=1.0: 1.0.1 from /usr/lib/python2.7/dist-packages
      ipaddress>=1.0.6: 1.0.14 from /usr/lib/python2.7/dist-packages
      ipaddress>=1.0.6: 1.0.14 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    setuptools: 38.4.0 from /usr/local/lib/python2.7/dist-packages
    Mopidy>=1.1: 2.1.0 from /usr/lib/python2.7/dist-packages
      Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
      requests>=2.0: 2.18.4 from /usr/local/lib/python2.7/dist-packages
        certifi>=2017.4.17: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
        chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/lib/python2.7/dist-packages
        idna<2.7,>=2.5: 2.6 from /usr/local/lib/python2.7/dist-packages
        urllib3<1.23,>=1.21.1: 1.22 from /usr/local/lib/python2.7/dist-packages
      tornado>=3.2: 4.5.3 from /usr/local/lib/python2.7/dist-packages
        singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
          six: 1.11.0 from /usr/local/lib/python2.7/dist-packages
        certifi: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
        backports_abc>=0.4: 0.5 from /usr/local/lib/python2.7/dist-packages
  ConfigObj>=5.0.6: 5.0.6 from /usr/local/lib/python2.7/dist-packages
    six: 1.11.0 from /usr/local/lib/python2.7/dist-packages
  raven>=6.1.0: 6.4.0 from /usr/local/lib/python2.7/dist-packages
    contextlib2; python_version < "3.2": 0.5.5 from /usr/local/lib/python2.7/dist-packages
  requests>=2.0.0: 2.18.4 from /usr/local/lib/python2.7/dist-packages
    certifi>=2017.4.17: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
    chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/lib/python2.7/dist-packages
    idna<2.7,>=2.5: 2.6 from /usr/local/lib/python2.7/dist-packages
    urllib3<1.23,>=1.21.1: 1.22 from /usr/local/lib/python2.7/dist-packages
Mopidy-TtsGpio: 1.0.2 from /usr/local/lib/python2.7/dist-packages
  setuptools: 38.4.0 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.18: 2.1.0 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests>=2.0: 2.18.4 from /usr/local/lib/python2.7/dist-packages
      certifi>=2017.4.17: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
      chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/lib/python2.7/dist-packages
      idna<2.7,>=2.5: 2.6 from /usr/local/lib/python2.7/dist-packages
      urllib3<1.23,>=1.21.1: 1.22 from /usr/local/lib/python2.7/dist-packages
    tornado>=3.2: 4.5.3 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.11.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
      backports_abc>=0.4: 0.5 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
Mopidy-Local-SQLite: 1.0.0 from /usr/lib/python2.7/dist-packages
  Mopidy>=1.1: 2.1.0 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests>=2.0: 2.18.4 from /usr/local/lib/python2.7/dist-packages
      certifi>=2017.4.17: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
      chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/lib/python2.7/dist-packages
      idna<2.7,>=2.5: 2.6 from /usr/local/lib/python2.7/dist-packages
      urllib3<1.23,>=1.21.1: 1.22 from /usr/local/lib/python2.7/dist-packages
    tornado>=3.2: 4.5.3 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.11.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
      backports_abc>=0.4: 0.5 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  uritools>=1.0: 1.0.1 from /usr/lib/python2.7/dist-packages
    ipaddress>=1.0.6: 1.0.14 from /usr/lib/python2.7/dist-packages
    ipaddress>=1.0.6: 1.0.14 from /usr/lib/python2.7/dist-packages
Mopidy-Moped: 0.7.1 from /usr/local/lib/python2.7/dist-packages
  setuptools: 38.4.0 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=1.0.0: 2.1.0 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests>=2.0: 2.18.4 from /usr/local/lib/python2.7/dist-packages
      certifi>=2017.4.17: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
      chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/lib/python2.7/dist-packages
      idna<2.7,>=2.5: 2.6 from /usr/local/lib/python2.7/dist-packages
      urllib3<1.23,>=1.21.1: 1.22 from /usr/local/lib/python2.7/dist-packages
    tornado>=3.2: 4.5.3 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.11.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
      backports_abc>=0.4: 0.5 from /usr/local/lib/python2.7/dist-packages
Mopidy-Local-Images: 1.0.0 from /usr/local/lib/python2.7/dist-packages
  uritools>=1.0: 1.0.1 from /usr/lib/python2.7/dist-packages
    ipaddress>=1.0.6: 1.0.14 from /usr/lib/python2.7/dist-packages
    ipaddress>=1.0.6: 1.0.14 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  setuptools: 38.4.0 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=1.1: 2.1.0 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests>=2.0: 2.18.4 from /usr/local/lib/python2.7/dist-packages
      certifi>=2017.4.17: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
      chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/lib/python2.7/dist-packages
      idna<2.7,>=2.5: 2.6 from /usr/local/lib/python2.7/dist-packages
      urllib3<1.23,>=1.21.1: 1.22 from /usr/local/lib/python2.7/dist-packages
    tornado>=3.2: 4.5.3 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.11.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
      backports_abc>=0.4: 0.5 from /usr/local/lib/python2.7/dist-packages
Mopidy-Spotify: 3.1.0 from /usr/lib/python2.7/dist-packages
  Mopidy>=2.0: 2.1.0 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests>=2.0: 2.18.4 from /usr/local/lib/python2.7/dist-packages
      certifi>=2017.4.17: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
      chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/lib/python2.7/dist-packages
      idna<2.7,>=2.5: 2.6 from /usr/local/lib/python2.7/dist-packages
      urllib3<1.23,>=1.21.1: 1.22 from /usr/local/lib/python2.7/dist-packages
    tornado>=3.2: 4.5.3 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.11.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
      backports_abc>=0.4: 0.5 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  pyspotify>=2.0.5: 2.0.5 from /usr/lib/python2.7/dist-packages
    cffi>=1.0.0: 1.1.2 from /usr/lib/python2.7/dist-packages
      pycparser: 2.10 from /usr/lib/python2.7/dist-packages
  requests>=2.0: 2.18.4 from /usr/local/lib/python2.7/dist-packages
    certifi>=2017.4.17: 2017.11.5 from /usr/local/lib/python2.7/dist-packages
    chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/lib/python2.7/dist-packages
    idna<2.7,>=2.5: 2.6 from /usr/local/lib/python2.7/dist-packages
    urllib3<1.23,>=1.21.1: 1.22 from /usr/local/lib/python2.7/dist-packages
GStreamer: 1.4.4.0 from /usr/lib/python2.7/dist-packages/gi
  Detailed information: 
    Python wrapper: python-gi 3.14.0
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mad
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec

**Comment by kingosticks** [comment]
It's now in the right place, you can see it's in the same place as iris. If you restart Mopidy it should now see the extension. If not, are there errors in the log?

**Comment by wt9bind** [comment]
Oh yep! That worked! Fantastic.

Thank you for all of your help!

**Comment by martijnboland** [comment]
Glad it's fixed, thanks @kingosticks for your help!
