### ISSUE TITLE
Search does not find artists

### ISSUE THREAD

**Issue by laclaro** [martijnboland/moped#77]
Hi,

I wonder why moped is not listing artists after a search. If I search for "Linking Park" or anything, it finds tracks and albums but not the artist itself.

Best,

Henning

**Comment by martijnboland** [comment]
Artist search works fine here:

<img width="891" alt="screen shot 2018-05-11 at 22 45 07" src="https://user-images.githubusercontent.com/167455/39946079-144d40ca-556d-11e8-810d-f315c3bf577d.png">

**Comment by martijnboland** [comment]
What mopidy version are you using?
